import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowUpRight, Menu, MessageCircle, X } from 'lucide-react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { site, whatsappUrl } from '../config/site'

const links = [['Home', '/'], ['Services', '/services'], ['About', '/about'], ['Contact', '/contact']]
export function Logo() { return <Link to="/" className="flex items-center gap-2.5 font-semibold tracking-tight text-ink" aria-label={`${site.name} home`}><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand text-sm font-bold text-white">N</span>{site.name}</Link> }
export function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const location = useLocation()
  useEffect(() => { setOpen(false) }, [location.pathname]); useEffect(() => { const fn = () => setScrolled(scrollY > 12); fn(); addEventListener('scroll', fn); return () => removeEventListener('scroll', fn) }, [])
  return <header className={`sticky top-0 z-40 transition-all ${scrolled ? 'border-b border-slate-200/80 bg-white/90 shadow-sm backdrop-blur-xl' : 'bg-white/75 backdrop-blur-md'}`}><div className="shell flex h-[72px] items-center justify-between gap-4"><Logo /><nav className="hidden items-center gap-1 lg:flex" aria-label="Primary">{links.map(([label, path]) => <NavLink key={path} to={path} className={({isActive}) => `rounded-lg px-3 py-2 text-sm font-medium transition ${isActive ? 'text-brand' : 'text-slate-600 hover:text-ink'}`}>{label}</NavLink>)}</nav><div className="flex items-center gap-2"><Link className="btn-primary hidden sm:inline-flex" to="/contact">Get Your Website <ArrowUpRight size={16}/></Link><button onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 lg:hidden" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X size={20}/> : <Menu size={20}/>}</button></div></div><AnimatePresence>{open && <motion.nav initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} className="overflow-hidden border-t border-slate-100 bg-white lg:hidden" aria-label="Mobile navigation"><div className="shell flex flex-col py-3">{links.map(([label,path]) => <NavLink key={path} to={path} className="rounded-lg px-3 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50">{label}</NavLink>)}<Link className="btn-primary mx-3 mt-3" to="/contact">Get Your Website <ArrowUpRight size={16}/></Link></div></motion.nav>}</AnimatePresence></header>
}
export function Footer() { return <footer className="border-t border-slate-200 bg-slate-950 pb-8 pt-14 text-slate-300"><div className="shell grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Link to="/" className="flex items-center gap-2.5 font-semibold text-white"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand text-sm font-bold">N</span>{site.name}</Link><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">{site.tagline}</p></div><FooterList title="Explore" items={links}/><FooterList title="Services" items={services}/><div><h3 className="text-sm font-semibold text-white">Contact</h3><div className="mt-4 space-y-2 text-sm"><a className="block hover:text-white" href={whatsappUrl}>WhatsApp</a><a className="block hover:text-white" href={`mailto:${site.email}`}>{site.email}</a><a className="block hover:text-white" href={`tel:${site.phone.replace(/\s/g,'')}`}>{site.phone}</a></div></div></div><div className="shell mt-12 flex flex-col gap-3 border-t border-slate-800 pt-6 text-xs text-slate-500 sm:flex-row sm:justify-between"><span>© 2026 {site.name}. All rights reserved.</span><span className="flex gap-5"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms & Conditions</Link></span></div></footer> }
function FooterList({title,items}:{title:string;items:(string[]|[string,string])[]}) { return <div><h3 className="text-sm font-semibold text-white">{title}</h3><div className="mt-4 space-y-2">{items.map((item) => { const [label,path] = item; return path ? <Link className="block text-sm hover:text-white" key={label} to={path}>{label}</Link> : <span className="block text-sm" key={label}>{label}</span> })}</div></div> }
const services = [['Clinic Websites',''],['Business Websites',''],['Restaurant Websites',''],['Portfolio Websites','']]
export function WhatsAppButton() { const reduced = useReducedMotion(); return <motion.a initial={reduced ? false : {scale:0}} animate={{scale:1}} transition={{delay:.5}} href={whatsappUrl} target="_blank" rel="noreferrer" className="group fixed bottom-5 right-5 z-30 flex h-14 items-center gap-2 rounded-full bg-[#25D366] px-4 text-white shadow-xl shadow-emerald-900/20" aria-label="Chat with us on WhatsApp"><MessageCircle size={24} fill="currentColor"/><span className="max-w-0 overflow-hidden whitespace-nowrap text-sm font-semibold transition-all group-hover:max-w-28">Chat with us</span></motion.a> }
export function PageMeta({title, description}:{title:string;description:string}) { useEffect(()=>{document.title=`${title} | ${site.name}`; const m=document.querySelector('meta[name="description"]');m?.setAttribute('content',description)},[title,description]); return null }
