import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, MessageCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { whatsappUrl } from '../config/site'

export function Reveal({children, className=''}:{children:React.ReactNode;className?:string}) { const reduced=useReducedMotion(); return <motion.div className={className} initial={reduced?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.55}}>{children}</motion.div> }
export function SectionHeading({eyebrow,title,copy,center=false}:{eyebrow?:string;title:string;copy?:string;center?:boolean}) { return <div className={`${center?'mx-auto text-center':''} max-w-2xl`}><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{copy&&<p className="copy mt-4">{copy}</p>}</div> }
export function CTA() { return <section className="pb-18 pt-8 sm:pb-24"><div className="shell"><Reveal><div className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-12 text-center sm:px-12 sm:py-16"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-blue-600/30 blur-3xl"/><div className="relative"><p className="eyebrow border-blue-400/20 bg-blue-500/15 text-blue-200">Let’s get started</p><h2 className="mx-auto max-w-2xl text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">Ready to Take Your Business Online?</h2><p className="mx-auto mt-4 max-w-xl text-slate-300">Tell us what you need and we'll help you build a website that fits your business.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/contact" className="btn-primary">Get Your Website <ArrowRight size={16}/></Link><a href={whatsappUrl} target="_blank" rel="noreferrer" className="btn-secondary border-white/15 bg-white/10 text-white hover:bg-white/20"><MessageCircle size={16}/> WhatsApp Us</a></div></div></div></Reveal></div></section> }
export function CheckItem({children}:{children:React.ReactNode}) { return <li className="flex gap-2 text-sm text-slate-600"><Check size={17} className="mt-.5 shrink-0 text-brand"/>{children}</li> }
